refdb_name: "MIDORI265"
marker_name: "Vences_16S_MIDORI265"
taxon_name: "Mammalia"
raw_refdb: "/Users/mikea/Documents/mikedata/refdb_geo/MIDORI2_UNIQ_NUC_GB265_lrRNA_RDP.fasta"
tax_dir: "/Users/mikea/Documents/mikedata/refdb_geo/mammals_Vences_16S/tax/"
tax_dl_date: "20250609"
results_dir: "/Users/mikea/Documents/mikedata/refdb_geo/Vences_16S_Mammalia/"
n_chunks: 1
fwd: "AGACGAGAAGACCCYdTGGAGCTT"
rev: "GATCCAACATCGAGGTCGTAA"
min_len: 100
max_len: 300
max_n: 10
pga_identity: 0.70
pga_cov: 0.95
pga_max_len: 20000
