name: refdb_geo
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11.7
  - snakemake
  - crabs
  - r-base=4.4.2
  - r-dplyr
  - r-biocmanager
  - r-devtools
  - r-tibble
  - r-tidyr
  - r-tictoc
  - r-ggplot2
  - r-patchwork
  - r-optparse
  - blast==2.16.0
  - r-rblast
  - bioconductor-biostrings
  - r-ape
  - r-argparse
  - r-sf
  - r-data.table
